### PR TITLE
5.x kernel update

### PR DESCRIPTION
**Pull request by oliver-rew**

### CODE REVIEW

**Comment by oliver-rew** [comment]
Don't review yet, WIP

**Comment by oliver-rew** [comment]
ready for review

**Review by ryanpdx — COMMENTED** [review]
Looks good!

I also tested it on a star tracker I had and it worked, so we are good to swap to the 5.10 kernel. Yay.

The minor changes to  do:

- Remove the empty `126` and `127` files
- Update `README.md` with correct kernel version and update the instructions.

**Comment by oliver-rew** [comment]
@ryanpdx good catches, updated

**Pull request merged**
